version: '3'
services:
  ms-livenes--non-reactive:
    image: ms-liveness-non-reactive:0.0.1-SNAPSHOT
    build: ./ms-liveness-non-reactive
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  mysql:
    container_name: mysql
    image: mysql
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: spring_jmeter
    volumes:
      - /Users/ridho/Documents/jmeter-test-result/db:/var/lib/mysql
    restart: unless-stopped