version: '3'
services:
  ms-livenes-non-reactive:
    image: ms-liveness-non-reactive:0.0.1-SNAPSHOT
    build: ./ms-liveness-non-reactive
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  ms-livenes-non-reactive-virtual-thread:
    image: virtualthread:0.0.1-SNAPSHOT
    build: ./virtualthread
    ports:
      - "8082:8080"
      - "8084:8084"
    env_file:
      - ./virtualthread/deploy/docker-dev.env
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  ms-livenes-reactive:
    image: ms-liveness:0.0.1-SNAPSHOT
    build: ./ms-liveness
    ports:
      - "8085:8080"
      - "8086:8086"
    env_file:
      - ./ms-liveness/deploy/docker-dev.env
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  mysql:
    container_name: mysql-service
    image: mysql:latest
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: spring_jmeter
    volumes:
      - /Users/ridho/Documents/jmeter-test-result/db:/var/lib/mysql
    restart: unless-stopped