version: '3'
services:
  non-reactive:
    image: non-reactive:0.0.1-SNAPSHOT
    build: ./non-reactive
    env_file:
      - ./non-reactive/deployment/docker-dev.env
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  virtual-thread:
    image: virtualthread:0.0.1-SNAPSHOT
    build: ./virtualthread
    ports:
      - "8082:8080"
      - "8083:8084"
    env_file:
      - ./virtualthread/deploy/docker-dev.env
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  reactive:
    image: reactive:0.0.1-SNAPSHOT
    build: ./reactive
    ports:
      - "8084:8080"
      - "8085:8086"
    env_file:
      - ./reactive/deploy/docker-dev.env
    deploy:
      resources:
        limits:
          cpus: '300m'
          memory: 512M
        reservations:
          cpus: '250m'
          memory: 128M
  mysql:
    container_name: mysql-service
    image: mysql:latest
    hostname: localhost
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: spring_jmeter
    volumes:
      - /Users/ridho/Documents/jmeter-test-result/db:/var/lib/mysql
    restart: unless-stopped